### ISSUE TITLE
Is this half-packery layout possible?

### ISSUE THREAD

**Issue by pistachiomatt** [metafizzy/packery#126]
A Metafizzy library is unparalleled in performance and reliability. So I’m motivated to ask: can Packery be pushed to make a layout like this?

![untitled](https://f.cloud.github.com/assets/170421/1808748/3da80c7a-6d73-11e3-9b30-597122fa3c90.png)

i.e. packed vertically, but gridded to height-unequal rows.

**Comment by brianfor44** [comment]
Hi @desandro, I just tried your suggested solution above and it works perfect. The only problem that I am having is that I want to use the imagesLoaded function first(otherwise, I have to resize the page at times for alignment to snap into place), but don't know how to then initialize the "new FitRows( element )" from there. Previously I had initialed from the html, but would prefer to do some from my js file. 

Thank you for any help with this!!!
