### ISSUE TITLE
dragItemPositioned event not being fired

### ISSUE THREAD

**Issue by waltermacambira** [metafizzy/packery#161]
In my example, I have a jQuery Draggable with containment. When I try to drag the last box to the right horizontally (until the end of the div - same as dragging it to a slot), I do not get an dragItemPositioned event.

You can look it here: http://codepen.io/anon/pen/KflFb

But I need an event when both cases occur (when you hit a slot, and when you don't). [**slot** = position of the grid created by rowHeight and columnWidth]

**Workaround**

If you remove the `if (needsPositioning)` before the emit of dragItemPositioned, the event is fired. I am worried if there is any collateral effect.

Any ideas?

Thank you

**Comment by UziTech** [comment]
I would also like to compact the items after dragging but when I call `$grid.packery()` in my "dragItemPositioned" function it compacts them then it moves the dragged item back to the dragged position.

If I change `$grid.packery()` to `setTimeout(function(){$grid.packery()}, 100)` it works.

Is there any way to tell it to always compact after drag?

**Comment by bwasilewski** [comment]
Just checking to see if this has been addressed at all? I am experiencing the same issue with the latest version (1.4.3).

**Comment by adrianhurt** [comment]
+1. I have the same issue. I have a set of "packery" items with Draggabilly option `containment: true`. If I drag any item to the top-left corner (i.e. position [0,0]), the event `dragItemPositioned` isn't fired. I understand that the dragged item doesn't need to be positioned, but the other ones do, and in fact they are fit to their corresponding new positions. I have tried to remove the `if` that noted @waltermacambira and it works perfectly.

I think it's better a "false positive" when you drag an item into exactly its old position than trigger absolutely nothing when a valid reordering has made. Otherwise, how could I get notified when the reordering has made?

As @waltermacambira said, is there any collateral effect that I am missing if we delete the previous `if (needsPositioning)`? What should be the difference between drag my first item into position [0,0] and [0,1]?

I would make a new PR, @desandro, but I prefer to wait to your response in case I am missing something.

Thanks!

**Comment by desandro** [comment]
I'm experimenting with a overhauled version of dragging that would resolve this ticket. Packery's drag behavior has been tweaked enough over the past 3 years that it needs a full clean up.

@adrianhurt I appreciate the interest, but I would hold off on working on a PR.

**Comment by adrianhurt** [comment]
Great!

**Comment by desandro** [comment]
[Packery v2 is out :tada: ](http://packery.metafizzy.co/) and has [all new drag behavior](https://twitter.com/desandro/status/694547335720751105). Dragging is way more intuitive. Dragged items will snap into position, reducing gaps. Other items shift up and down, so no more random movement. Plus, Packery adds a [drop placeholder](http://packery.metafizzy.co/draggable.html#drop-placeholder) so you can display where the item is going to land.

Time to close this one up! Thanks for your interest over the years. If you run into any issues with the new drag behavior, please open a new issue :grin:
