### ISSUE TITLE
Position items with percent values. Nicer when resizing

### ISSUE THREAD

**Issue by jerzygangi** [metafizzy/packery#236]
When a user drags his mouse to resize the browser window, packery waits for the user to stop dragging before triggering a re-layout based on the new window width. This can lead to ugly layouts while the user is in mid-drag.

Is there any way to constantly trigger a re-layout while the window is being resized?

**Comment by desandro** [comment]
Hi there! Thanks for this feature request. Rather than constantly triggering `layout`, I think a better solution would be to position items with percent values (as opposed to pixels). This has been requested for Masonry desandro/masonry#574

I've got a working example: http://codepen.io/desandro/pen/EamjJJ

This adds a new option, `percentPosition: true`. It sets position of the column in percentage. To use the code, add the `Outlayer.Item.prototype.layoutPosition` code.

If others would like to see this feature merged into production, please **+1**

**Comment by desandro** [comment]
Packery v1.4 now has [`percentPosition` option](http://packery.metafizzy.co/options.html#percentposition). See demo http://codepen.io/desandro/pen/tonpx
