### ISSUE TITLE
Percent Position dynamic height without animation bounce/transition

### ISSUE THREAD

**Issue by angiefu2** [metafizzy/packery#294]
Hey! 

I'm currently using Percent Position for my packery grid, trying to make tiles that remain at a 1:1 ratio. I included some jquery to make this possible, but I'm not sure how to resolve the overlapping/bounce that happens between the tiles vertically. I know that
<code>"percentPosition": true</code> resolves this issue horizontally, but I'm not sure I understand how to fix this issue vertically.

You can see an example of the issue here:http://codepen.io/anon/pen/BNXWrN
You probably have to first resize the browser for the tiles to stop them from overlapping. It should look like this after resize: 
<img width="1061" alt="screen shot 2015-08-24 at 11 24 30 pm" src="https://cloud.githubusercontent.com/assets/6532154/9444107/57a6ece0-4ab7-11e5-811f-dea981e4e070.png">

I have to warn that I am a JS and JQ novice, so apologies in advance if this is an issue that's been tended to. I appreciate any guidance!

**Comment by desandro** [comment]
Hello! Thanks for submitting this issue.

Good news is that everything is behaving normally. When you resize the window, the delay is there so that JS behavior is not triggered every millisecond during resizing. Having all layout be super smooth when re-sizing the window looks nice, but isn't necessary for your users. The delay keeps your page behaving speedily, which is good for users.

I forked your CodePen to simplify it: http://codepen.io/desandro/pen/JdgJBN

+ Removed percentPosition code (this is now in Packery by default)
+ Used `padding-bottom` CSS hack for responsive width/height ratio

**Comment by angiefu2** [comment]
You're right—I think simpler is better in this case. Thanks for the help! :+1:

**Comment by EugeneDae** [comment]
Thanks so much @angiefu2 and @desandro, that codepen saved me writing a JS handler :+1:
