### ISSUE TITLE
Blank space when loading more images. 

### ISSUE THREAD

**Issue by rarevalo1** [metafizzy/packery#308]
Hey guys, 

Just a quick question, I'm seeing some odd behavior in the way a packery styled gallery loads certain images, take a look here: 

https://www.evernote.com/l/Aox-YDYtrOJNqazFvcAxe2xoF77QlJY5yrg

Not sure if posting here is fine or if you have a different way of helping me out with this issue.

**Comment by desandro** [comment]
That gap is likely caused by a pixel rounding error. Try setting or un-setting `columnWidth` or `rowHeight`. Provide a **reduced test case** so others could take a look as well. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/packery/blob/master/contributing.md#submitting-issues).
