### ISSUE TITLE
initLayout: false prevents adding new items

### ISSUE THREAD

**Issue by alvarotrigo** [metafizzy/packery#371]
I was trying to follow the steps you detail [on this post](https://github.com/metafizzy/packery/issues/337) in order to restore items position after saving them and I found out that when using `initLayout: false` the addition of new elements no longer works. 

I get the following error message:
```shell
packery.pkgd.min.js:12 Uncaught TypeError: Cannot read property 'paddingLeft' of undefined
```

[Reproduction online](http://jsfiddle.net/1kxzf2d4/3/)

I'm using packery v2.0.0.
I found no method to turn `initLayout` to true after the initial load of items, is there any solution to this issue?

**Comment by desandro** [comment]
Thanks for reporting this issue. The problem is that you cannot use `appended` before the initial `layout` is triggered. `initLayout: false` is useful if you want to do things before that initial layout, like change the layout, or bind events. In the [save position demo](http://codepen.io/desandro/pen/PZrXVv), you can see that the initial layout is triggered in

``` js
$grid.packery( 'initShiftLayout', initPositions, 'data-item-id' );
```

This idea works just as well for your demo, adding [`$grid.packery()`](http://packery.metafizzy.co/methods.html#layout-packery). See demo http://jsfiddle.net/1kxzf2d4/4/

Since nothing is happening before the initial layout, you can also resolve this by re-enabling `initLayout: true`.

**Comment by alvarotrigo** [comment]
Thanks for the quick reply Desandro!
I managed to solve that issue, but I found another one. Not quite sure if I should better post this in the `save and load sorting` topic.

Look at this problem:
![notworking](https://cloud.githubusercontent.com/assets/1706326/14739773/be7c94b4-0881-11e6-9588-e5e1bea30668.gif)


You can reproduce it on [this fiddle](http://jsfiddle.net/1kxzf2d4/7/).

**Comment by desandro** [comment]
Thanks for finding this issue. I believe this is being caused by the initial size of the grid. After forcing a scroll bar with `html { overflow-y: scroll; }` it looks like its resolved. Can you try http://jsfiddle.net/1kxzf2d4/8/ ?

**Comment by alvarotrigo** [comment]
Awesome! That solves the problem!

Now I found another one. After saving the position by dragging them, then reload the site to retrieve the sorting data but this time when an smaller viewport. Things get pretty ugly:

![resized](https://cloud.githubusercontent.com/assets/1706326/14740999/0737f762-088b-11e6-9962-6b927070d281.JPG)

**Comment by alvarotrigo** [comment]
I'll close the issue as it is kind of the same as https://github.com/metafizzy/packery/issues/337 and it seems there's no easy solution for this anyway.
