### ISSUE TITLE
Ability to control packery ordering (i.e. bin packing)

### ISSUE THREAD

**Issue by coolwebs** [metafizzy/packery#386]
I've looked thoroughly at the documentation and I can't seem to find any mention of being able to control the Packery ordering. There is reference to "Stamp" but that is not what I am looking for.

Currently making mockups and I've got three 1/3 grid items at the bottom that I would like to stay close to each other as a group and not fly around to fill different areas of the layout based on the bin packing algorithm.

So far the only way I have been able to achieve this is by taking them out of the 'grid-item' flow and just doing my own responsive CSS on them.

Is there any way to control the order of the grid elements when Packery is sorting them based on available space?

**Comment by desandro** [comment]
Thanks for submitting this issue. There may be several solutions

+ As you mentioned, these items could sit outside of the Packery grid
+ You can put the three items into their own item element, so they are positioned together, rather than separate
+ You could stamp the items
+ You can [Isotope with packery layout mode](http://isotope.metafizzy.co/layout-modes/packery.html) and a [sorting function](http://isotope.metafizzy.co/sorting.html#getsortdata-functions)
