### ISSUE TITLE
License clarifications

### ISSUE THREAD

**Issue by matchdav** [metafizzy/packery#407]
You say on the site that if a commercial website is using Packery, they should be purchasing a commercial license, and that the GPL3 is only for personal and open-source projects.  

However, licensing your work under the GPL3 actually allows anyone to use your code on any website as long as they aren't redistributing the source.  Running code on a website does not constitute redistribution; the GPL doesn't cover that.  See [this FAQ answer](https://www.gnu.org/licenses/gpl-faq.html#GPLRequireSourcePostedPublic)

Your intention isn't clear to me.  If you don't want people using your code on commercial websites (e.g. let's say I want to run it on my Shopify site where I sell T-shirts) for free, you shouldn't be hosting it on github and licensing it under GPL3.  If you're more concerned about redistribution in packages like Atom etc. then you should make that more clear.

**Comment by desandro** [comment]
Thank you for this feedback. My intention is to make money so I can make a living, which in turns allows me to keep working on Metafizzy and its libraries.

The trouble is finding a way to make money from front-end development. Creating a successful licensing model that works for front-end development is hard. Nearly all other front-end projects are open-source. But keeping Metafizzy's code, documentation, and demos open-source and freely available, I enable users and potential customers to try everything out for themselves.

I chose to go with GPLv3 for open source because WordPress developers and themers need GPL.  Since making this move last year, I haven't heard as many issues about the licensing model. So now I have to deal with the intricacies of the GPL.

I could go about the decisions behind the licensing model, but I'll just say this: I've been doing this for five years, longer than most start-ups last, and this is the best solution I've found thus far. I'll continue to evaluate the license terms and the commercial model.
