### ISSUE TITLE
Reduced case: Packery doesn't work with % heights

### ISSUE THREAD

**Issue by corysimmons** [metafizzy/packery#437]
https://codepen.io/corysimmons/pen/qmdjKG

**Comment by desandro** [comment]
Thanks for reporting this issue.

Indeed, Packery does not work with percent heights (for vertical Packery layouts). This is a circular logic issue. Packery requires items to have explicit pixel heights, so it can measure their size and figure out where to put the items. Packery also resizes the container based on the items heights.

If items had percent heights, then the container would have to have a height. But Packery sets that height. That's why Packery requires items to have set heights.

You can disable this behavior by setting `resizeContainer: false`. See demo https://codepen.io/desandro/pen/6caf6dc518a81f4f6965370d45c829ff/

`resizeContainer` is an undocumented option. Sorry, I don't know how useful it is 😝 

As for your demo, Packery is not designed to work with flexbox CSS.

**Comment by corysimmons** [comment]
I can work with this, thanks David. 👍
