### ISSUE TITLE
Bring Isotope sorting into Packery, or Packery Drag and Drop into Isotope

### ISSUE THREAD

**Issue by atomorbit** [metafizzy/packery#46]
You've mentioned that you'll bring a packery layout into Isotope, but that seems to target the gap issue and not drag and drop.

If I want the beauty of both drag and drop ordering, with dynamic filtering and sorting at the same time, is there a roadmap for that?

Can I help?

**Comment by imjoeybrennan** [comment]
My use case for wanting the draggability with filtering and sorting options would be not to use both draggability and filtering and sorting in one view but use each option in two separate scenarios of gridded items. One scenario would be sorting/filtering for a view where dragging wouldn't be necessary and the other would be dragging where filtering/sorting wouldn't be necessary. Just seems like including both packery and isotope would be sort of redundant since both have the same basic layouts. Let me know if you think including both isn't really redundant from your perspective.

**Comment by dcworldwide** [comment]
:+1:

**Comment by rohan-deshpande** [comment]
+ 1 for this feature. I don't think it's unreasonable to support both dragging, sorting and filtering. For a use case, let's take a real like example; I have a bunch of post it notes on a board. There's 12 notes and 3 colours of post its, pink, yellow and blue. Now maybe I only want to see the blue post its, but when I remove the other colours, now I want to order the post it notes so that the most urgent one is first. Currently I can't do this with isotope. I think it's a valuable feature and would love to see it implemented.

**Comment by kalenjohnson** [comment]
I have a similar use case as those already mentioned. However, I'm thinking that it does present some technical barriers.

For the last example of post it notes, we can safely assume that the post it notes with different colors are all mixed together. Blue - yellow - pink - pink - blue - blue -yellow, etc. We filter to show only the blue post it notes. Then we proceed to sort. However, in what order are the blue post it notes in comparison with the rest? IE. in a physical sense, if you took your blue post it notes and sorted them separately from the other post it notes, how would they fit back in when showing ALL the post it notes? Do they automatically get pushed to the front/top ? somehow intermingle in the middle? Or do some type of more complicated algorithm where if a blue post it note is placed before the first blue post it note, would it be then moved to the post it note order before whatever was in front of the original blue note?

Makes my head hurt a little.

How I think I'll solve it is to use both metafizzy packages. I'll have Isotope display a set of images with tags which will be filterable. However, to modify the overall order of the images, I'll perhaps open a modal with all of the images in a smaller thumbnail view and use Packery to drag and drop sort them. When the user is done sorting, he can save the order and refresh the Isotope list of images.

**Comment by 7ruth** [comment]
+1

**Comment by daweedm** [comment]
+1

**Comment by alexiskattan** [comment]
-1 agree with the author
