### ISSUE TITLE
Overlapping boxes

### ISSUE THREAD

**Issue by negarjf** [metafizzy/packery#504]
**Test case:** https://codepen.io/negarjf/pen/aKVMgQ

I am using **Packery** in a bootstrap project. When resizing the window, especially on break-points, some boxes overlap. This problem will fix automatically on next action (drop or resize). But it could be annoying for users.
![screenshot 45](https://user-images.githubusercontent.com/24963113/41580891-da7934ae-73b1-11e8-8b9c-a5cad3191bf3.png)

I''m not sure if I'm missing something or it's a functional bug. I am using Chrome Version 67.

**Comment by desandro** [comment]
Thanks for reporting this issue.

I've seen this issue before. What's happening is that the size of the boxes is being squished horizontally, because of the changing window size, which causes text to grow more narrow and thus taller vertically.

One way to address this problem is set `percentPosition: true`. This way, items move a little bit with changing window size. It doesn't completely resolve the issue, but most of the overlapping is fixed.
